---
# this role sets up the Meshtastic daemon on Raspberry Pi SBCs
# reading variables from bitwarden secrets manager

- name: 'Get Meshtastic MQTT details from Bitwarden'
  set_fact:
    mqtt:
      host: "{{ lookup('community.general.bitwarden', 'meshtastic:mqtt:meshnet', field='server') }}"
      username: "{{ lookup('community.general.bitwarden', 'meshtastic:mqtt:meshnet', field='username') }}"
      password: "{{ lookup('community.general.bitwarden', 'meshtastic:mqtt:meshnet', field='password') }}"
      topic: "{{ lookup('community.general.bitwarden', 'meshtastic:mqtt:meshnet', field='topic') }}"

- name: Add Meshtastic APT repository
  ansible.builtin.apt_repository:
    repo: "deb http://download.opensuse.org/repositories/network:/Meshtastic:/beta/Debian_12/ /"
    state: present
    filename: "network:Meshtastic:beta"

- name: Add Meshtastic GPG key
  ansible.builtin.get_url:
    url: "https://download.opensuse.org/repositories/network:Meshtastic:beta/Debian_12/Release.key"
    dest: "/etc/apt/trusted.gpg.d/network_Meshtastic_beta.gpg"
    mode: '0644'

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Meshtastic daemon
  ansible.builtin.apt:
    name: meshtasticd
    state: present