---
# this role sets up the MeshCore prerequisites on Raspberry Pi SBCs
# reading variables from bitwarden secrets manager

- name: Ensure SPI is enabled in /boot/firmware/config.txt
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtparam=spi='
    line: 'dtparam=spi=on'
    state: present

- name: Ensure SPI overlay is set in /boot/firmware/config.txt
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    line: 'dtoverlay=spi0-0cs'
    state: present

- name: Install RPI GPIO
  become: true
  ansible.builtin.apt:
    name: rpi.gpio-common
    state: latest

- name: Install required packages
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-dev
      - python3-venv
      - libffi-dev 
      - libssl-dev
    state: latest
    update_cache: true
    autoremove: true