---
all:
  vars:
    #ansible_user: ansible
    #ansible_ssh_pass: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='password') | first }}"

rpi:
  hosts:
    10.100.0.168:
  vars:
    ansible_user: ddulfer
    
meshcore:
  hosts:
    10.100.0.168:
  vars:
    ansible_user: ddulfer

meshtastic:
  hosts:
    10.100.0.168:
  vars:
    ansible_user: ddulfer

proxmox_nodes:
  hosts:
    192.168.41.11:
    192.168.41.12:
    192.168.41.13:
    192.168.41.14:
  vars:
    ansible_user: root