- name: Create Ansible user with sudo privileges
  hosts: all
  remote_user: "{{ ansible_user }}"
  become: yes

  vars_prompt:
    - name: "remote_pass"
      prompt: "Enter the password for the remote host"
      private: yes
  
  vars:
    ansible_ssh_pass: "{{ remote_pass }}"
      
  tasks:
    - name: 'Get Ansible user credentials from Bitwarden'
      set_fact:
        ansible_user_username: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='username') | first }}"
        ansible_user_password: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='password') | first }}"

    # make sure sudo is installed
    - name: Install sudo
      apt:
        name: sudo
        state: present

    # add ansible user with sudo privileges and use credentials from ansible_user facts
    - name: Add ansible user with sudo privileges
      ansible.builtin.user:
        name: "{{ ansible_user_username }}"
        state: present
        groups: sudo
        append: yes
        comment: "Ansible configuration management user"
        shell: /bin/bash
        password: "{{ ansible_user_password | password_hash('sha512') }}"
        update_password: on_create

    # Configure sudo access without password
    - name: Allow ansible user sudo without password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        line: "{{ ansible_user_username }} ALL=(ALL) NOPASSWD:ALL"
        state: present
        mode: '0440'
        create: yes
        validate: '/usr/sbin/visudo -cf %s'