- name: Create Ansible user with sudo privileges
  hosts: all
  remote_user: "{{ ansible_user }}"

  vars_prompt:
    - name: "remote_pass"
      prompt: "Enter the password for the remote host"
      private: yes
  
  vars:
    ansible_ssh_pass: "{{ remote_pass }}"
      
  tasks:
    - name: 'Get Ansible user credentials from Bitwarden'
      set_fact:
        ansible_user_username: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='username') | first }}"
        ansible_user_password: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='password') | first }}"

    # ensure sudo is installed on host
    - name: apt update
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    
    - name: Install sudo
      apt:
        name: sudo
        state: present

    # add ansible user with sudo privileges and use credentials from ansible_user facts
    - name: Add ansible user with sudo privileges
      ansible.builtin.user:
        name: "{{ ansible_user_username }}"
        state: present
        groups: sudo
        comment: "Ansible configuration management user"
        shell: /bin/bash
        password: "{{ ansible_user_password | password_hash('sha512') }}"
        update_password: on_create
        
    # add user 'ansible' to sudo group
    - name: Add ansible user to sudo group
      ansible.builtin.user:
        name: "{{ ansible_user_username }}"
        groups: sudo
        append: yes
