---
- name: Setup Raspberry Pi SBC as Meshtastic node
  hosts: meshtastic
  remote_user: "{{ ansible_user }}"
  become: yes

  roles:
   - meshtastic

  vars_prompt:
    - name: "remote_pass"
      prompt: "Enter the password for the remote host"
      private: yes

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: Update apt cache and perform upgrades
      apt:
        update_cache: yes
        upgrade: dist  
        autoremove: yes
        autoclean: yes
        clean: yes     
    
    #ensure avahi-daemon is installed
    - name: Install avahi-daemon
      apt:
        name: avahi-daemon
        state: present

    # disable avahi-daemon ipv6 support in /etc/avahi/avahi-daemon.conf
    - name: Disable avahi-daemon ipv6 support
      lineinfile:
        path: /etc/avahi/avahi-daemon.conf
        regexp: '^use-ipv6=yes'
        insertafter: '^#use-ipv6=yes'
        line: use-ipv6=no
      register: avahi_daemon
    
    # if /etc/avahi/avahi-daemon.conf was changed, restart avahi-daemon
    - name: Restart avahi-daemon
      service:
        name: avahi-daemon
        state: restarted
        enabled: yes
      when: avahi_daemon.changed

    - name: Install git package
      apt:
        name: git
        state: present
        