---
- name: Prepare Raspberry Pi SBC for MeshCore node
  hosts: meshcore
  remote_user: "ansible"
  gather_facts: no
  become: true 

  roles:
   - meshcore

  vars:
    ansible_user: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='username') | first }}"
    ansible_ssh_pass: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='password') | first }}"
    ansible_become_password: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='password') | first }}"

  pre_tasks:
        
    - name: Install git package
      apt:
        name: git
        state: present
    
    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present