---
- name: Setup Raspberry Pi SBC as Meshtastic node
  hosts: meshtastic
  remote_user: "ansible"
  gather_facts: no
  become: true 

  roles:
   - meshtastic

  vars:
    ansible_user: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='username') | first }}"
    ansible_ssh_pass: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='password') | first }}"
    ansible_become_password: "{{ lookup('community.general.bitwarden', 'linux:ansible', field='password') | first }}"

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    #ensure avahi-daemon is installed
    - name: Install avahi-daemon
      apt:
        name: avahi-daemon
        state: present

    # disable avahi-daemon ipv6 support in /etc/avahi/avahi-daemon.conf
    - name: Disable avahi-daemon ipv6 support
      lineinfile:
        path: /etc/avahi/avahi-daemon.conf
        regexp: '^use-ipv6=yes'
        insertafter: '^#use-ipv6=yes'
        line: use-ipv6=no
      register: avahi_daemon
    
    # if /etc/avahi/avahi-daemon.conf was changed, restart avahi-daemon
    - name: Restart avahi-daemon
      service:
        name: avahi-daemon
        state: restarted
        enabled: yes
      when: avahi_daemon.changed

    - name: Install git package
      apt:
        name: git
        state: present
        